# Actuator Configuration
# Ref: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    enabled-by-default: false                 # defaults it to false and expose only what you want
    web:
      exposure:
        include:
        - health
        - prometheus
